---
title: "N Rate Trial"
author: "Zhang Zhenglin"
output:
  pdf_document:
    toc: yes
  html_notebook:
    toc: yes
    toc_float: yes
editor_options:
  markdown:
    wrap: sentence
---

# Necessary libraries

```{r echo=FALSE,message=FALSE,warning=FALSE}
library(knitr)
library(ggplot2)
theme_set(theme_bw())
library(emmeans)
library(multcomp)
library(PLS205)
library(lme4)
library(lmerTest)
library(multcompView)
library(car)
library(Rmisc) 
library(dplyr) #https://r4ds.had.co.nz/ (Chapter 3, Chapter 5, look at filter and select)
# https://bookdown.org/ansellbr/WEHI_tidyR_course_book/
library(stringr) 
library(data.table)
library(GGally)
library(formatR)
library(readxl)
library(mgcv)
library(xlsx)

```

# Data Organisation

## Read from excel

```{r}
master <- read_excel("Grain yield for Dustin.xlsx", sheet = 1)
master <- mutate_if(master, is.character, as.factor)
master$NrateF <- as.factor(master$Nrate)
master$Year <- as.factor(master$Year)

str(master)
```


# Initial visualisation

```{r}
ggplot(master, aes(y=Yield_kgha, x=Nrate, color=Field))+ 
  geom_point()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size= 9))
```

# Check for most important variables

> Year effect very significant. So analyse data by 3 different years. 

```{r}
all_factors_model <- lm(Yield_kgha~Year*NrateF*Field, data = master)

anova(all_factors_model)
```

# Subset data from the 3 years

```{r}
yield_2021 <- master %>% filter (Year == "2021")

yield_2022 <- master %>% filter (Year == "2022")

yield_2023 <- master %>% filter (Year == "2023")

#checked datasets, all looks good. 
```

# statistical testing 

## 2021

```{r}
model_2021 <- lmer(Yield_kgha ~ NrateF+Field:NrateF+(1|Field:Blk)+(1|NrateF:Blk), data=yield_2021)

field_means_2021 = emmeans(model_2021,spec = 'Field',by = 'NrateF')
field_effects_2021 = contrast(field_means_2021, method = 'pairwise', adjust = "Tukey")

summary(field_effects_2021) 
cld(field_means_2021)
```


## 2022

```{r}
model_2022 <- lmer(Yield_kgha ~ NrateF+Field:NrateF+(1|Field:Blk)+(1|NrateF:Blk), data=yield_2022)

field_means_2022 = emmeans(model_2022,spec = 'Field',by = 'NrateF')
field_effects_2022 = contrast(field_means_2022, method = 'pairwise', adjust = "Tukey")

summary(field_effects_2022) 
cld(field_means_2022)
```

## 2023

```{r}
model_2023 <- lmer(Yield_kgha ~ NrateF+Field:NrateF+(1|Field:Blk)+(1|NrateF:Blk), data=yield_2023)

field_means_2023 = emmeans(model_2023,spec = 'Field',by = 'NrateF')
field_effects_2023 = contrast(field_means_2023, method = 'pairwise', adjust = "Tukey")

summary(field_effects_2023) 
cld(field_means_2023)
```

# Graphing dataframes

```{r}
# 2021 dataframe

yield_2021_dataframe <- yield_2021 %>% 
    group_by(Field, Nrate) %>% 
   mutate(Yield_kgha_sd = sd(Yield_kgha)) %>% 
  summarise(Yield_kgha = mean(Yield_kgha),
            Yield_kgha_sd = mean(Yield_kgha_sd)) %>%
  mutate(Year = 2021)

# 2022 dataframe

yield_2022_dataframe <- yield_2022 %>% 
    group_by(Field, Nrate) %>% 
   mutate(Yield_kgha_sd = sd(Yield_kgha)) %>% 
  summarise(Yield_kgha = mean(Yield_kgha),
            Yield_kgha_sd = mean(Yield_kgha_sd)) %>%
  mutate(Year = 2022)

# 2023 dataframe

yield_2023_dataframe <- yield_2023 %>% 
    group_by(Field, Nrate) %>% 
   mutate(Yield_kgha_sd = sd(Yield_kgha)) %>% 
  summarise(Yield_kgha = mean(Yield_kgha),
            Yield_kgha_sd = mean(Yield_kgha_sd)) %>%
  mutate(Year = 2023)
```
# Graphs

## 2021 graph 

```{r}

N_response_curve_2021 <- 
ggplot(yield_2021_dataframe, aes(x=Nrate, y=Yield_kgha, color=Field))+
  geom_point(data=yield_2021_dataframe, size=2.5)+
  scale_color_manual(values=c("#0072B2","#FFCC66"), name = "Field", labels = c('Continous Rice','Fallow Rice'))+
  scale_x_continuous(name="N Rate kgN/ha", limits = c(-5, 280), breaks = c(0, 115, 155, 185, 225, 260))+ #limits = c(0, 
  scale_y_continuous(name= "Yield (kg/ha)", limits = c(0, 16000))+ #, limits = c(0, 16000), expand = c(0, 0), breaks =
  geom_errorbar(data=yield_2021_dataframe, aes(ymin=Yield_kgha-Yield_kgha_sd, ymax=Yield_kgha+Yield_kgha_sd), width=8, size=0.7)+
  theme_classic()+theme(axis.text = element_text(size = 10), axis.title = element_text(size=10))+
  geom_smooth(data = yield_2021, method = "lm", formula = y ~ poly(x, 2), se = TRUE, alpha=0.2)+
  #geom_vline(xintercept = c(0, 115, 155, 185, 225, 260), linetype = "dashed", color = "black") +
  theme(legend.text = element_text(size = 10),legend.title = element_text(size = 14))

N_response_curve_2021

ggsave(N_response_curve_2021, filename = "N_response_curve_2021.png", height = 15, width = 20, units = "cm")
```

## 2022 graph 

```{r}

N_response_curve_2022 <- 
ggplot(yield_2022_dataframe, aes(x=Nrate, y=Yield_kgha, color=Field))+
  geom_point(data=yield_2022_dataframe, size=2.5)+
  scale_color_manual(values=c("#0072B2","#FFCC66"), name = "Field", labels = c('Continous Rice','Fallow Rice'))+
  scale_x_continuous(name="N Rate kgN/ha", limits = c(-5, 280), breaks = c(0, 115, 155, 185, 225, 260))+ #limits = c(0, 
  scale_y_continuous(name= "Yield (kg/ha)", limits = c(0, 16000))+ #, limits = c(0, 16000), expand = c(0, 0), breaks =
  geom_errorbar(data=yield_2022_dataframe, aes(ymin=Yield_kgha-Yield_kgha_sd, ymax=Yield_kgha+Yield_kgha_sd), width=8, size=0.7)+
  theme_classic()+theme(axis.text = element_text(size = 10), axis.title = element_text(size=10))+
  geom_smooth(data = yield_2022, method = "lm", formula = y ~ poly(x, 2), se = TRUE, alpha=0.2)+
  #geom_vline(xintercept = c(0, 115, 155, 185, 225, 260), linetype = "dashed", color = "black") +
  theme(legend.text = element_text(size = 10),legend.title = element_text(size = 14))

N_response_curve_2022

ggsave(N_response_curve_2022, filename = "N_response_curve_2022.png", height = 15, width = 20, units = "cm")
```

## 2023 graph 

```{r}
N_response_curve_2023 <- 
ggplot(yield_2023_dataframe, aes(x=Nrate, y=Yield_kgha, color=Field))+
  geom_point(data=yield_2023_dataframe, size=2.5)+
  scale_color_manual(values=c("#0072B2","#FFCC66"), name = "Field", labels = c('Continous Rice','Fallow Rice'))+
  scale_x_continuous(name="N Rate kgN/ha", limits = c(-5, 280), breaks = c(0, 90, 120, 150, 180, 210))+ #limits = c(0, 
  scale_y_continuous(name= "Yield (kg/ha)", limits = c(0, 16000))+ #, limits = c(0, 16000), expand = c(0, 0), breaks =
  geom_errorbar(data=yield_2023_dataframe, aes(ymin=Yield_kgha-Yield_kgha_sd, ymax=Yield_kgha+Yield_kgha_sd), width=8, size=0.7)+
  theme_classic()+theme(axis.text = element_text(size = 10), axis.title = element_text(size=10))+
  geom_smooth(data = yield_2023, method = "lm", formula = y ~ poly(x, 2), se = TRUE, alpha=0.2)+
  #geom_vline(xintercept = c(0, 90, 120, 150, 180, 210), linetype = "dashed", color = "black") +
  theme(legend.text = element_text(size = 10),legend.title = element_text(size = 14))

N_response_curve_2023

ggsave(N_response_curve_2023, filename = "N_response_curve_2023.png", height = 15, width = 20, units = "cm")
```


